using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;

namespace Scribe.Scriptorium;

/// <summary>
///     Meta-generator. Runs at Scribe's own compile time. Scans
///     <c>Scribe.Shapes.ShapeBuilder</c> for every <c>Must*</c> primitive and
///     emits severity variants into a partial class:
///     <list type="bullet">
///         <item><c>Must*</c> (positive)  →  <c>Should*</c> (Warning) + <c>Could*</c> (Info)</item>
///         <item><c>MustNot*</c>           →  <c>ShouldNot*</c> (Warning) only</item>
///     </list>
///     Each variant delegates to the handwritten <c>Must*</c> method, overriding
///     only the severity when the caller has not supplied one.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class ShapeBuilderVariantsGenerator : IIncrementalGenerator
{
    private const string ShapeBuilderMetadataName = "Scribe.Shapes.ShapeBuilder";
    private const string DiagnosticSpecFqn = "Scribe.Shapes.DiagnosticSpec";

    // FullyQualifiedFormat minus UseSpecialTypes, so `System.String` doesn't collapse to the
    // `string` keyword — we need the real type name to be able to prepend `global::`.
    private static readonly SymbolDisplayFormat FullyQualifiedNoKeywords = new(
        globalNamespaceStyle: SymbolDisplayGlobalNamespaceStyle.Included,
        typeQualificationStyle: SymbolDisplayTypeQualificationStyle.NameAndContainingTypesAndNamespaces,
        genericsOptions: SymbolDisplayGenericsOptions.IncludeTypeParameters,
        miscellaneousOptions: SymbolDisplayMiscellaneousOptions.EscapeKeywordIdentifiers
            | SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var source = context.CompilationProvider
            .Select((comp, ct) => BuildSource(comp, ct));

        context.RegisterSourceOutput(source, (spc, src) =>
        {
            if (!string.IsNullOrEmpty(src))
            {
                spc.AddSource("ShapeBuilder.Variants.g.cs", src!);
            }
        });
    }

    private static string? BuildSource(Compilation compilation, CancellationToken ct)
    {
        var shapeBuilder = compilation.GetTypeByMetadataName(ShapeBuilderMetadataName);
        if (shapeBuilder is null)
        {
            return null;
        }

        var candidates = shapeBuilder.GetMembers()
            .OfType<IMethodSymbol>()
            .Where(IsVariantTarget)
            .OrderBy(m => m.Name, StringComparer.Ordinal)
            .ToList();

        if (candidates.Count == 0)
        {
            return null;
        }

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by Scribe.Scriptorium — do not edit />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Microsoft.CodeAnalysis;");
        sb.AppendLine();
        sb.AppendLine("namespace Scribe.Shapes;");
        sb.AppendLine();
        sb.AppendLine("partial class ShapeBuilder");
        sb.AppendLine("{");

        var first = true;
        foreach (var method in candidates)
        {
            ct.ThrowIfCancellationRequested();
            if (!first)
            {
                sb.AppendLine();
            }

            first = false;
            EmitVariants(sb, method);
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static bool IsVariantTarget(IMethodSymbol method)
    {
        if (method.DeclaredAccessibility != Accessibility.Public
            || method.IsStatic
            || method.MethodKind != MethodKind.Ordinary)
        {
            return false;
        }

        if (!method.Name.StartsWith("Must", StringComparison.Ordinal))
        {
            return false;
        }

        if (method.ReturnType.ToDisplayString() != ShapeBuilderMetadataName)
        {
            return false;
        }

        // Final parameter must be a DiagnosticSpec? — that's the override hook.
        var lastParam = method.Parameters.LastOrDefault();
        if (lastParam is null)
        {
            return false;
        }

        var type = lastParam.Type;
        if (type is not INamedTypeSymbol named
            || named.OriginalDefinition.SpecialType != SpecialType.System_Nullable_T
            || named.TypeArguments.Length != 1
            || named.TypeArguments[0].ToDisplayString() != DiagnosticSpecFqn)
        {
            return false;
        }

        return true;
    }

    private static void EmitVariants(StringBuilder sb, IMethodSymbol method)
    {
        var isNegative = method.Name.StartsWith("MustNot", StringComparison.Ordinal);
        var bareName = isNegative ? method.Name.Substring("MustNot".Length) : method.Name.Substring("Must".Length);

        if (isNegative)
        {
            EmitOne(sb, method, variantPrefix: "ShouldNot", bareName: bareName, severity: "Warning",
                summary: $"Warning-level variant of <see cref=\"{FormatXmlRef(method)}\"/>.");
        }
        else
        {
            EmitOne(sb, method, variantPrefix: "Should", bareName: bareName, severity: "Warning",
                summary: $"Warning-level variant of <see cref=\"{FormatXmlRef(method)}\"/>.");
            sb.AppendLine();
            EmitOne(sb, method, variantPrefix: "Could", bareName: bareName, severity: "Info",
                summary: $"Info-level variant of <see cref=\"{FormatXmlRef(method)}\"/>.");
        }
    }

    private static void EmitOne(
        StringBuilder sb,
        IMethodSymbol method,
        string variantPrefix,
        string bareName,
        string severity,
        string summary)
    {
        var newName = variantPrefix + bareName;

        sb.Append("    /// <summary>").Append(summary).AppendLine("</summary>");

        sb.Append("    public global::Scribe.Shapes.ShapeBuilder ").Append(newName);
        AppendTypeParameters(sb, method);
        sb.Append('(');
        AppendParameterList(sb, method);
        sb.AppendLine(")");

        AppendTypeParameterConstraints(sb, method);

        sb.Append("        => ").Append(method.Name);
        AppendTypeParameters(sb, method);
        sb.Append('(');
        AppendForwardingArgs(sb, method, severity);
        sb.AppendLine(");");
    }

    private static void AppendTypeParameters(StringBuilder sb, IMethodSymbol method)
    {
        if (method.TypeParameters.Length == 0)
        {
            return;
        }

        sb.Append('<');
        for (var i = 0; i < method.TypeParameters.Length; i++)
        {
            if (i > 0)
            {
                sb.Append(", ");
            }

            sb.Append(method.TypeParameters[i].Name);
        }

        sb.Append('>');
    }

    private static void AppendTypeParameterConstraints(StringBuilder sb, IMethodSymbol method)
    {
        foreach (var tp in method.TypeParameters)
        {
            var parts = new List<string>();
            if (tp.HasReferenceTypeConstraint)
            {
                parts.Add("class");
            }

            if (tp.HasValueTypeConstraint)
            {
                parts.Add("struct");
            }

            if (tp.HasNotNullConstraint)
            {
                parts.Add("notnull");
            }

            if (tp.HasUnmanagedTypeConstraint)
            {
                parts.Add("unmanaged");
            }

            foreach (var ct in tp.ConstraintTypes)
            {
                parts.Add(ct.ToDisplayString(FullyQualifiedNoKeywords));
            }

            if (tp.HasConstructorConstraint)
            {
                parts.Add("new()");
            }

            if (parts.Count == 0)
            {
                continue;
            }

            sb.Append("        where ").Append(tp.Name).Append(" : ").AppendLine(string.Join(", ", parts));
        }
    }

    private static void AppendParameterList(StringBuilder sb, IMethodSymbol method)
    {
        for (var i = 0; i < method.Parameters.Length; i++)
        {
            if (i > 0)
            {
                sb.Append(", ");
            }

            var p = method.Parameters[i];
            sb.Append(p.Type.ToDisplayString(FullyQualifiedNoKeywords));
            sb.Append(' ').Append(p.Name);

            if (p.HasExplicitDefaultValue)
            {
                sb.Append(" = ").Append(FormatDefault(p.ExplicitDefaultValue, p.Type));
            }
        }
    }

    private static void AppendForwardingArgs(StringBuilder sb, IMethodSymbol method, string severity)
    {
        var last = method.Parameters.Length - 1;
        for (var i = 0; i < method.Parameters.Length; i++)
        {
            if (i > 0)
            {
                sb.Append(", ");
            }

            var p = method.Parameters[i];
            if (i == last)
            {
                sb.Append("global::Scribe.Shapes.SeverityVariants.WithSeverity(")
                    .Append(p.Name)
                    .Append(", global::Microsoft.CodeAnalysis.DiagnosticSeverity.")
                    .Append(severity)
                    .Append(')');
            }
            else
            {
                sb.Append(p.Name);
            }
        }
    }

    private static string FormatDefault(object? value, ITypeSymbol type)
    {
        if (value is null)
        {
            return type.IsValueType && type.OriginalDefinition.SpecialType != SpecialType.System_Nullable_T
                ? "default"
                : "null";
        }

        return value switch
        {
            bool b => b ? "true" : "false",
            string s => "\"" + s.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"",
            _ => value.ToString() ?? "default",
        };
    }

    private static string FormatXmlRef(IMethodSymbol method)
    {
        var builder = new StringBuilder();
        builder.Append("Scribe.Shapes.ShapeBuilder.").Append(method.Name);
        if (method.TypeParameters.Length > 0)
        {
            builder.Append('{');
            for (var i = 0; i < method.TypeParameters.Length; i++)
            {
                if (i > 0)
                {
                    builder.Append(',');
                }

                builder.Append(method.TypeParameters[i].Name);
            }

            builder.Append('}');
        }

        return builder.ToString();
    }
}
