using Scribe;

namespace Scribe.Tests;

public sealed class QuillTests
{
    // ── Inscribe / Header ──────────────────────────────────────────────────

    [Fact]
    public void Inscribe_EmitsAutoGeneratedHeader()
    {
        var result = new Quill().Inscribe();

        result.ShouldStartWith("// <auto-generated/>");
        result.ShouldContain("#nullable enable");
    }

    [Fact]
    public void Inscribe_DefaultHeader_EmitsMinimalAttribution()
    {
        var result = new Quill().Inscribe();

        result.ShouldContain("// I,");
        result.ShouldContain("// ~ THE SCRIBE");
    }

    [Fact]
    public void Inscribe_WithHeader_EmitsPageHeader()
    {
        var result = new Quill().Header("My Generator").Inscribe();

        result.ShouldContain("My Generator");
        result.ShouldContain("IN COLLABORATION WITH");
        result.ShouldContain("~ THE SCRIBE");
        result.ShouldContain("github.com/BulletsForHumanity/Scribe");
        result.ShouldContain("HEREBY ANNOUNCE");
    }

    [Fact]
    public void Inscribe_WithMultiLineHeader_EmitsAllLines()
    {
        var result = new Quill().Header("HERMETIC\nA domain-driven development kit\nhttps://github.com/BulletsForHumanity/Hermetic").Inscribe();

        result.ShouldContain("HERMETIC");
        result.ShouldContain("A domain-driven development kit");
        result.ShouldContain("github.com/BulletsForHumanity/Hermetic");
        result.ShouldContain("HEREBY ANNOUNCE");
    }

    [Fact]
    public void Inscribe_WithHeader_DynamicWidth_ShortHeader()
    {
        var result = new Quill().Header("HG").Inscribe();

        // URL is the longest line — box width should accommodate it
        result.ShouldContain("https://github.com/BulletsForHumanity/Scribe");
        result.ShouldContain("HG");
    }

    [Fact]
    public void Inscribe_WithHeader_DynamicWidth_LongHeader()
    {
        var longHeader = "A Very Long Generator Name That Exceeds The URL Length Considerably";
        var result = new Quill().Header(longHeader).Inscribe();

        // Box should expand to fit the long header
        result.ShouldContain(longHeader);
        result.ShouldContain("HEREBY ANNOUNCE");
    }

    [Fact]
    public void Inscribe_AlwaysEndsWithIHaveSpoken()
    {
        var withoutHeader = new Quill().Inscribe();
        withoutHeader.TrimEnd().ShouldEndWith("// I HAVE SPOKEN");

        var withHeader = new Quill().Header("Test").Inscribe();
        withHeader.TrimEnd().ShouldEndWith("// I HAVE SPOKEN");
    }

    [Fact]
    public void Inscribe_CanOnlyBeCalledOnce()
    {
        var q = new Quill();
        q.Inscribe();

        Should.Throw<InvalidOperationException>(() => q.Inscribe());
    }

    // ── Namespace ────────────────────────────────────────────────────────

    [Fact]
    public void FileNamespace_EmitsFileScopedNamespace()
    {
        var q = new Quill();
        q.FileNamespace("MyApp.Generated");
        var result = q.Inscribe();

        result.ShouldContain("namespace MyApp.Generated;");
    }

    [Fact]
    public void FileNamespace_EmptyString_DoesNotEmitNamespace()
    {
        var q = new Quill();
        q.FileNamespace("");
        var result = q.Inscribe();

        result.ShouldNotContain("namespace");
    }

    // ── Usings ───────────────────────────────────────────────────────────

    [Fact]
    public void Using_EmitsSortedUsings()
    {
        var q = new Quill();
        q.Using("System.Linq");
        q.Using("System.Collections.Generic");
        var result = q.Inscribe();

        var linqIdx = result.IndexOf("using System.Collections.Generic;", StringComparison.Ordinal);
        var genIdx = result.IndexOf("using System.Linq;", StringComparison.Ordinal);
        linqIdx.ShouldBeLessThan(genIdx);
    }

    [Fact]
    public void Using_DeduplicatesDuplicates()
    {
        var q = new Quill();
        q.Using("System.Linq");
        q.Using("System.Linq");
        var result = q.Inscribe();

        var count = result.Split("using System.Linq;").Length - 1;
        count.ShouldBe(1);
    }

    [Fact]
    public void Usings_AddsMultiple()
    {
        var q = new Quill();
        q.Usings("System", "System.Linq");
        var result = q.Inscribe();

        result.ShouldContain("using System;");
        result.ShouldContain("using System.Linq;");
    }

    // ── Line ─────────────────────────────────────────────────────────────

    [Fact]
    public void Line_EmitsTextAtCurrentIndent()
    {
        var q = new Quill();
        q.Line("public class Foo { }");
        var result = q.Inscribe();

        result.ShouldContain("public class Foo { }");
    }

    [Fact]
    public void Line_EmptyString_EmitsBlankLine()
    {
        var q = new Quill();
        q.Line("first");
        q.Line();
        q.Line("second");
        var result = q.Inscribe();

        result.ShouldContain("first");
        result.ShouldContain("second");
    }

    // ── Lines (multi-line string) ────────────────────────────────────────

    [Fact]
    public void Lines_RawString_DedentsAndIndents()
    {
        var q = new Quill();
        using (q.Block("public class Foo"))
        {
            q.Lines(
                """
                var x = 1;
                var y = 2;
                """
            );
        }

        var result = q.Inscribe();
        result.ShouldContain("    var x = 1;");
        result.ShouldContain("    var y = 2;");
    }

    [Fact]
    public void Lines_Padded_InsertsBlankLinesAroundContent()
    {
        var q = new Quill();
        using (q.Block("public class Foo"))
        {
            q.Line("var a = 0;");
            q.Lines(
                    """
                    var x = 1;
                    var y = 2;
                    """
                )
                .Padded();
            q.Line("var z = 3;");
        }

        var result = q.Inscribe();
        var nl = Quill.NewLine;
        // Verify blank line before the padded content
        result.ShouldContain($"var a = 0;{nl}{nl}    var x = 1;");
        // Verify blank line after the padded content
        result.ShouldContain($"var y = 2;{nl}{nl}    var z = 3;");
    }

    [Fact]
    public void Lines_ParamsArray_EmitsEachLine()
    {
        var q = new Quill();
        q.Lines("first", "second", "third");
        var result = q.Inscribe();

        result.ShouldContain("first");
        result.ShouldContain("second");
        result.ShouldContain("third");
    }

    // ── LinesFor ─────────────────────────────────────────────────────────

    [Fact]
    public void LinesFor_EmitsOneLinePerItem()
    {
        var q = new Quill();
        var items = new[] { "Alpha", "Beta", "Gamma" };
        q.LinesFor(items, x => $"// {x}");
        var result = q.Inscribe();

        result.ShouldContain("// Alpha");
        result.ShouldContain("// Beta");
        result.ShouldContain("// Gamma");
    }

    [Fact]
    public void LinesFor_Padded_WrapsInBlankLines()
    {
        var q = new Quill();
        q.Line("before");
        q.LinesFor(["item"], x => x).Padded();
        q.Line("after");
        var result = q.Inscribe();

        var nl = Quill.NewLine;
        result.ShouldContain($"before{nl}{nl}item{nl}{nl}after");
    }

    // ── Comment ──────────────────────────────────────────────────────────

    [Fact]
    public void Comment_EmitsSlashSlashComment()
    {
        var q = new Quill();
        q.Comment("hello world");
        var result = q.Inscribe();

        result.ShouldContain("// hello world");
    }

    [Fact]
    public void Comment_AddsBlankLineSeparation()
    {
        var q = new Quill();
        q.Line("var x = 1;");
        q.Comment("section");
        var result = q.Inscribe();

        result.ShouldContain($"var x = 1;{Quill.NewLine}{Quill.NewLine}// section");
    }

    // ── AppendRaw ────────────────────────────────────────────────────────

    [Fact]
    public void AppendRaw_EmitsVerbatim()
    {
        var q = new Quill();
        q.AppendRaw("raw content here");
        var result = q.Inscribe();

        result.ShouldContain("raw content here");
    }

    // ── ListInit ─────────────────────────────────────────────────────────

    [Fact]
    public void ListInit_EmitsCollectionInitializer()
    {
        var q = new Quill();
        var items = new[] { "\"A\"", "\"B\"" };
        q.ListInit("var list", "new List<string>", items, x => x);
        var result = q.Inscribe();

        result.ShouldContain("var list = new List<string>");
        result.ShouldContain("{");
        result.ShouldContain("\"A\",");
        result.ShouldContain("\"B\",");
        result.ShouldContain("};");
    }

    // ── Block ────────────────────────────────────────────────────────────

    [Fact]
    public void Block_EmitsHeaderBracesAndIndent()
    {
        var q = new Quill();
        using (q.Block("public class Foo"))
        {
            q.Line("public int X { get; }");
        }

        var result = q.Inscribe();
        result.ShouldContain("public class Foo");
        result.ShouldContain("{");
        result.ShouldContain("    public int X { get; }");
        result.ShouldContain("}");
    }

    [Fact]
    public void Block_NestedBlocks_IndentCorrectly()
    {
        var q = new Quill();
        using (q.Block("namespace Foo"))
        {
            using (q.Block("public class Bar"))
            {
                q.Line("public int X { get; }");
            }
        }

        var result = q.Inscribe();
        result.ShouldContain("    public class Bar");
        result.ShouldContain("        public int X { get; }");
    }

    [Fact]
    public void Block_MultiLineHeader_DedentsAndIndents()
    {
        var q = new Quill();
        using (
            q.Block(
                """
                public static bool TryParse(
                    string? s,
                    out Foo result)
                """
            )
        )
        {
            q.Line("result = default;");
        }

        var result = q.Inscribe();
        result.ShouldContain("public static bool TryParse(");
        result.ShouldContain("    string? s,");
        result.ShouldContain("    out Foo result)");
    }

    [Fact]
    public void Block_TrimsTrailingBlankLinesBeforeClose()
    {
        var q = new Quill();
        using (q.Block("public class Foo"))
        {
            q.Line("var x = 1;");
            q.Line(); // trailing blank
            q.Line(); // trailing blank
        }

        var result = q.Inscribe();
        // Should have exactly one newline between last content and }
        result.ShouldNotContain($"var x = 1;{Quill.NewLine}{Quill.NewLine}{Quill.NewLine}}}");

    }

    // ── Scope ────────────────────────────────────────────────────────────

    [Fact]
    public void Scope_EmitsBareBlockWithoutHeader()
    {
        var q = new Quill();
        using (q.Scope())
        {
            q.Line("var x = 1;");
        }

        var result = q.Inscribe();
        result.ShouldContain("{");
        result.ShouldContain("    var x = 1;");
        result.ShouldContain("}");
    }

    // ── Case ─────────────────────────────────────────────────────────────

    [Fact]
    public void Case_EmitsCaseWithBreak()
    {
        var q = new Quill();
        using (q.Case("\"foo\""))
        {
            q.Line("DoFoo();");
        }

        var result = q.Inscribe();
        result.ShouldContain("case \"foo\":");
        result.ShouldContain("{");
        result.ShouldContain("    DoFoo();");
        result.ShouldContain("    break;");
        result.ShouldContain("}");
    }

    // ── Indent ───────────────────────────────────────────────────────────

    [Fact]
    public void Indent_IncreasesAndRestoresIndent()
    {
        var q = new Quill();
        q.Line("outer");
        using (q.Indent())
        {
            q.Line("inner");
        }

        q.Line("outer again");
        var result = q.Inscribe();

        result.ShouldContain($"outer{Quill.NewLine}    inner{Quill.NewLine}outer again");
    }

    // ── XML Documentation (BlockScope post-decoration) ───────────────────

    [Fact]
    public void Summary_InsertsXmlDocBeforeBlockHeader()
    {
        var q = new Quill();
        using (q.Block("public void Foo()").Summary("Does the foo thing."))
        {
            q.Line("// body");
        }

        var result = q.Inscribe();
        result.ShouldContain("/// <summary>Does the foo thing.</summary>");
        var summaryIdx = result.IndexOf("/// <summary>", StringComparison.Ordinal);
        var headerIdx = result.IndexOf("public void Foo()", StringComparison.Ordinal);
        summaryIdx.ShouldBeLessThan(headerIdx);
    }

    [Fact]
    public void Summary_MultiLine_InsertsExpandedXmlDoc()
    {
        var q = new Quill();
        using (q.Block("public void Foo()").Summary("First line.\nSecond line."))
        {
            q.Line("// body");
        }

        var result = q.Inscribe();
        result.ShouldContain("/// <summary>");
        result.ShouldContain("///     First line.");
        result.ShouldContain("///     Second line.");
        result.ShouldContain("/// </summary>");
    }

    [Fact]
    public void Param_InsertsParamDoc()
    {
        var q = new Quill();
        using (q.Block("public void Foo(int x)").Summary("Does foo.").Param("x", "The value."))
        {
            q.Line("// body");
        }

        var result = q.Inscribe();
        result.ShouldContain("/// <param name=\"x\">The value.</param>");
    }

    [Fact]
    public void TypeParam_InsertsTypeParamDoc()
    {
        var q = new Quill();
        using (q.Block("public void Foo<T>()").TypeParam("T", "The type."))
        {
            q.Line("// body");
        }

        var result = q.Inscribe();
        result.ShouldContain("/// <typeparam name=\"T\">The type.</typeparam>");
    }

    [Fact]
    public void Returns_InsertsReturnsDoc()
    {
        var q = new Quill();
        using (q.Block("public int Foo()").Returns("The value."))
        {
            q.Line("return 42;");
        }

        var result = q.Inscribe();
        result.ShouldContain("/// <returns>The value.</returns>");
    }

    [Fact]
    public void Remarks_InsertsRemarksDoc()
    {
        var q = new Quill();
        using (q.Block("public void Foo()").Remarks("Important note."))
        {
            q.Line("// body");
        }

        var result = q.Inscribe();
        result.ShouldContain("/// <remarks>Important note.</remarks>");
    }

    [Fact]
    public void XmlDoc_InsertsBlankLineSeparationFromPreviousContent()
    {
        var q = new Quill();
        using (q.Block("public class Foo"))
        {
            q.Line("public int X { get; }");
            using (q.Block("public void Bar()").Summary("Does bar."))
            {
                q.Line("// body");
            }
        }

        var result = q.Inscribe();
        // There should be a blank line between X and the summary
        result.ShouldContain($"public int X {{ get; }}{Quill.NewLine}{Quill.NewLine}    /// <summary>");
    }

    // ── ContentResult implicit conversion ────────────────────────────────

    [Fact]
    public void ContentResult_ImplicitConversion_AllowsFluent()
    {
        var q = new Quill();
        // Lines() returns ContentResult, which should implicitly convert to Quill
        Quill returned = q.Lines(
            """
            var x = 1;
            """
        );

        returned.ShouldBeSameAs(q);
    }

    // ── Global Reference Resolution ────────────────────────────────────
    //
    // ResolveGlobalReferences only shortens global:: references whose namespace
    // is already registered via Using()/Usings(). Unregistered global:: refs
    // stay as-is — the generator author must register the namespaces they need.

    [Fact]
    public void Global_ResolvesGlobalRefs_ToShortNames()
    {
        var q = new Quill();
        q.Using("System.Collections.Generic");
        q.Line("var x = new global::System.Collections.Generic.List<int>();");
        var result = q.Inscribe();

        result.ShouldContain("using System.Collections.Generic;");
        result.ShouldContain("var x = new List<int>();");
        result.ShouldNotContain("global::");
    }

    [Fact]
    public void Global_ResolvesMultipleDistinctRefs()
    {
        var q = new Quill();
        q.Usings("System", "System.Text.Json");
        q.Line("global::System.Guid id = default;");
        q.Line("global::System.Text.Json.JsonSerializer.Serialize(id);");
        var result = q.Inscribe();

        result.ShouldContain("using System;");
        result.ShouldContain("using System.Text.Json;");
        result.ShouldContain("Guid id = default;");
        result.ShouldContain("JsonSerializer.Serialize(id);");
        result.ShouldNotContain("global::");
    }

    [Fact]
    public void Global_UnregisteredNamespace_StaysAsIs()
    {
        var q = new Quill();
        // No Using() call — global:: should stay
        q.Line("global::Foo.Bar.Widget w = default;");
        var result = q.Inscribe();

        result.ShouldContain("global::Foo.Bar.Widget w = default;");
    }

    [Fact]
    public void Global_DeduplicatesSameTypeUsedMultipleTimes()
    {
        var q = new Quill();
        q.Using("System");
        q.Line("global::System.Guid a = default;");
        q.Line("global::System.Guid b = default;");
        var result = q.Inscribe();

        result.ShouldContain("using System;");
        var count = result.Split("using System;").Length - 1;
        count.ShouldBe(1);
        result.ShouldContain("Guid a = default;");
        result.ShouldContain("Guid b = default;");
        result.ShouldNotContain("global::");
    }

    [Fact]
    public void Global_PreservesManualUsings_AlongsideResolved()
    {
        var q = new Quill();
        q.Usings("System", "System.Linq");
        q.Line("global::System.Guid id = default;");
        var result = q.Inscribe();

        result.ShouldContain("using System;");
        result.ShouldContain("using System.Linq;");
        result.ShouldContain("Guid id = default;");
    }

    [Fact]
    public void Global_NoGlobalRefs_DoesNotAddUsings()
    {
        var q = new Quill();
        q.Line("var x = 42;");
        var result = q.Inscribe();

        result.ShouldNotContain("using System;");
        result.ShouldContain("var x = 42;");
    }

    [Fact]
    public void Global_MemberAccess_ResolvedCorrectlyWithUsing()
    {
        // global::System.Globalization.CultureInfo.InvariantCulture — CultureInfo is a type,
        // InvariantCulture is a static property. With "System.Globalization" registered,
        // the global:: prefix is stripped and the remainder is CultureInfo.InvariantCulture.
        var q = new Quill();
        q.Using("System.Globalization");
        q.Line("var c = global::System.Globalization.CultureInfo.InvariantCulture;");
        var result = q.Inscribe();

        result.ShouldContain("using System.Globalization;");
        result.ShouldContain("var c = CultureInfo.InvariantCulture;");
        result.ShouldNotContain("global::");
    }

    [Fact]
    public void Global_MemberAccess_WithoutUsing_StaysAsIs()
    {
        // Without a registered using, global:: stays — no guessing.
        var q = new Quill();
        q.Line("var c = global::System.Globalization.CultureInfo.InvariantCulture;");
        var result = q.Inscribe();

        result.ShouldContain("global::System.Globalization.CultureInfo.InvariantCulture");
    }

    [Fact]
    public void Global_InGenericTypeArgument_ResolvesCorrectly()
    {
        var q = new Quill();
        q.Usings("System", "System.Collections.Generic");
        q.Line("var items = new global::System.Collections.Generic.List<global::System.Guid>();");
        var result = q.Inscribe();

        result.ShouldContain("using System;");
        result.ShouldContain("using System.Collections.Generic;");
        result.ShouldContain("var items = new List<Guid>();");
        result.ShouldNotContain("global::");
    }

    [Fact]
    public void Global_InNestedGenerics_ResolvesAll()
    {
        var q = new Quill();
        q.Using("System.Collections.Generic");
        q.Line("var x = new global::System.Collections.Generic.Dictionary<string, global::System.Collections.Generic.List<int>>();");
        var result = q.Inscribe();

        result.ShouldContain("using System.Collections.Generic;");
        result.ShouldContain("var x = new Dictionary<string, List<int>>();");
        result.ShouldNotContain("global::");
    }

    [Fact]
    public void Global_InInterfaceList_ResolvesCorrectly()
    {
        var q = new Quill();
        q.Using("System");
        q.Line("public partial record Amount : global::System.IParsable<Amount>, global::System.IComparable<Amount>");
        var result = q.Inscribe();

        result.ShouldContain("using System;");
        result.ShouldContain(
            "public partial record Amount : IParsable<Amount>, IComparable<Amount>"
        );
        result.ShouldNotContain("global::");
    }

    [Fact]
    public void Global_NullableType_ResolvesCorrectly()
    {
        var q = new Quill();
        q.Using("System");
        q.Line("public static bool TryParse(string? s, global::System.IFormatProvider? provider, out Amount result)");
        var result = q.Inscribe();

        result.ShouldContain("using System;");
        result.ShouldContain("IFormatProvider? provider");
        result.ShouldNotContain("global::");
    }

    [Fact]
    public void Global_InConstructor_ResolvesCorrectly()
    {
        var q = new Quill();
        q.Using("System");
        q.Line("throw new global::System.ArgumentException(\"bad\", nameof(value));");
        var result = q.Inscribe();

        result.ShouldContain("using System;");
        result.ShouldContain("throw new ArgumentException(\"bad\", nameof(value));");
        result.ShouldNotContain("global::");
    }

    [Fact]
    public void Global_InTypeof_ResolvesCorrectly()
    {
        var q = new Quill();
        q.Using("System");
        q.Line("if (type == typeof(global::System.Guid))");
        var result = q.Inscribe();

        result.ShouldContain("if (type == typeof(Guid))");
        result.ShouldNotContain("global::");
    }

    [Fact]
    public void Global_SameNamespaceMultipleTypes_SingleUsing()
    {
        var q = new Quill();
        q.Using("System");
        q.Line("global::System.Guid id = default;");
        q.Line("throw new global::System.ArgumentException(\"bad\");");
        q.Line("global::System.IntPtr ptr = default;");
        var result = q.Inscribe();

        // Should only have one "using System;" even though 3 types use it
        var count = result.Split("using System;").Length - 1;
        count.ShouldBe(1);
        result.ShouldNotContain("global::");
    }

    [Fact]
    public void Global_LongestNamespaceMatchWins()
    {
        // When both "System" and "System.Text.Json" are registered,
        // "global::System.Text.Json.JsonSerializer" should match the longer namespace.
        var q = new Quill();
        q.Usings("System", "System.Text.Json");
        q.Line("global::System.Text.Json.JsonSerializer.Serialize(id);");
        var result = q.Inscribe();

        result.ShouldContain("JsonSerializer.Serialize(id);");
        // Should NOT produce "Text.Json.JsonSerializer" from matching "System" only
        result.ShouldNotContain("Text.Json.JsonSerializer");
        result.ShouldNotContain("global::");
    }

    [Fact]
    public void Global_InMultiLineBlock_ResolvesAcrossLines()
    {
        var q = new Quill();
        q.Usings("System.Threading", "System.Threading.Tasks");
        using (q.Block("public global::System.Threading.Tasks.Task RunAsync(global::System.Threading.CancellationToken cancellationToken)"))
        {
            q.Line("return Task.CompletedTask;");
        }

        var result = q.Inscribe();

        result.ShouldContain("using System.Threading;");
        result.ShouldContain("using System.Threading.Tasks;");
        result.ShouldContain("public Task RunAsync(CancellationToken cancellationToken)");
        result.ShouldContain("    return Task.CompletedTask;");
        result.ShouldNotContain("global::");
    }

    [Fact]
    public void Global_WithStaticPropertyAccess_ResolvesWithRegisteredUsing()
    {
        // With the namespace registered, global::System.StringComparison.Ordinal
        // correctly becomes StringComparison.Ordinal.
        var q = new Quill();
        q.Using("System");
        q.Line("string.Equals(a, b, global::System.StringComparison.Ordinal);");
        var result = q.Inscribe();

        result.ShouldContain("using System;");
        result.ShouldContain("string.Equals(a, b, StringComparison.Ordinal);");
        result.ShouldNotContain("global::");
    }

    [Fact]
    public void Global_UsingsAreSorted()
    {
        var q = new Quill();
        q.Usings("System", "System.Collections.Generic", "System.Threading.Tasks");
        q.Line("global::System.Threading.Tasks.Task t = default;");
        q.Line("global::System.Collections.Generic.List<int> l = default;");
        q.Line("global::System.Guid g = default;");
        var result = q.Inscribe();

        var sysIdx = result.IndexOf("using System;", StringComparison.Ordinal);
        var genIdx = result.IndexOf("using System.Collections.Generic;", StringComparison.Ordinal);
        var taskIdx = result.IndexOf("using System.Threading.Tasks;", StringComparison.Ordinal);
        sysIdx.ShouldBeLessThan(genIdx);
        genIdx.ShouldBeLessThan(taskIdx);
    }

    // ── Alias ───────────────────────────────────────────────────────────

    [Fact]
    public void Alias_ExplicitAlias_EmitsUsingAlias()
    {
        var q = new Quill();
        var w = q.Alias("Foo.Bar", "Widget", "FooWidget");
        q.Line($"{w} x = default;");
        var result = q.Inscribe();

        result.ShouldContain("using FooWidget = Foo.Bar.Widget;");
        result.ShouldContain("FooWidget x = default;");
    }

    [Fact]
    public void Alias_AutoGenerated_UsesLastNamespaceSegment()
    {
        var q = new Quill();
        var w = q.Alias("Foo.Bar", "Widget");
        q.Line($"{w} x = default;");
        var result = q.Inscribe();

        result.ShouldContain("using BarWidget = Foo.Bar.Widget;");
        result.ShouldContain("BarWidget x = default;");
    }

    [Fact]
    public void Alias_AutoGenerated_WalksUpOnConflict()
    {
        var q = new Quill();
        var w1 = q.Alias("A.Utils", "Helper");
        var w2 = q.Alias("B.Utils", "Helper");
        q.Line($"{w1} h1 = default;");
        q.Line($"{w2} h2 = default;");
        var result = q.Inscribe();

        // First registration gets UtilsHelper (last ns segment), second conflicts
        // and walks up to BUtilsHelper.
        w1.ShouldBe("UtilsHelper");
        w2.ShouldBe("BUtilsHelper");
        result.ShouldContain("using UtilsHelper = A.Utils.Helper;");
        result.ShouldContain("using BUtilsHelper = B.Utils.Helper;");
        result.ShouldContain("UtilsHelper h1 = default;");
        result.ShouldContain("BUtilsHelper h2 = default;");
    }

    [Fact]
    public void Alias_ReturnsSameAlias_ForDuplicateRegistration()
    {
        var q = new Quill();
        var a1 = q.Alias("System", "Guid");
        var a2 = q.Alias("System", "Guid");
        a1.ShouldBe(a2);
    }

    [Fact]
    public void Alias_ExplicitAlias_ReturnValue_IsAliasName()
    {
        var q = new Quill();
        var result = q.Alias("System", "Guid", "MyGuid");
        result.ShouldBe("MyGuid");
    }

    [Fact]
    public void Alias_CoexistsWithGlobalResolution()
    {
        var q = new Quill();
        q.Using("System");
        var w = q.Alias("Foo.Bar", "Widget", "FooWidget");
        q.Line($"{w} a = default;");
        q.Line("global::System.Guid id = default;");
        var result = q.Inscribe();

        result.ShouldContain("using FooWidget = Foo.Bar.Widget;");
        result.ShouldContain("using System;");
        result.ShouldContain("FooWidget a = default;");
        result.ShouldContain("Guid id = default;");
        result.ShouldNotContain("global::");
    }

    // ── Full integration: realistic output ───────────────────────────────

    [Fact]
    public void FullIntegration_ProducesCorrectOutput()
    {
        var q = new Quill();
        q.Using("System");
        q.FileNamespace("TestDomain");

        using (q.Block("public partial record Amount : global::System.IParsable<Amount>"))
        {
            using (
                q.Block("public static Amount Create(decimal value)")
                    .Summary("Creates a new Amount.")
            )
            {
                q.Lines(
                    """
                    if (value == default)
                        throw new global::System.ArgumentException("bad", nameof(value));
                    return new Amount(value);
                    """
                );
            }

            q.Line("public static implicit operator decimal(Amount value) => value.Value;");
        }

        var result = q.Inscribe();

        result.ShouldContain("// <auto-generated/>");
        result.ShouldContain("using System;");
        result.ShouldContain("namespace TestDomain;");
        result.ShouldContain("/// <summary>Creates a new Amount.</summary>");
        result.ShouldContain("public partial record Amount : IParsable<Amount>");
        result.ShouldContain("        throw new ArgumentException(\"bad\", nameof(value));");
        result.ShouldContain(
            "    public static implicit operator decimal(Amount value) => value.Value;"
        );
        result.ShouldNotContain("global::");
    }

    // ── Standalone TypeParam ─────────────────────────────────────────────

    [Fact]
    public void TypeParam_Standalone_EmitsTypeParamDoc()
    {
        var q = new Quill();
        q.TypeParam("T", "The element type.");
        q.Line("public void Foo<T>() { }");
        var result = q.Inscribe();

        result.ShouldContain("/// <typeparam name=\"T\">The element type.</typeparam>");
    }

    // ── Standalone Returns ───────────────────────────────────────────────

    [Fact]
    public void Returns_Standalone_EmitsReturnsDoc()
    {
        var q = new Quill();
        q.Returns("The computed value.");
        q.Line("public int Compute() => 42;");
        var result = q.Inscribe();

        result.ShouldContain("/// <returns>The computed value.</returns>");
    }

    // ── BlockScope InheritDoc ────────────────────────────────────────────

    [Fact]
    public void InheritDoc_BlockScope_InsertsBeforeHeader()
    {
        var q = new Quill();
        using (q.Block("public override string ToString()").InheritDoc())
        {
            q.Line("return Value;");
        }

        var result = q.Inscribe();
        result.ShouldContain("/// <inheritdoc />");
        var inheritIdx = result.IndexOf("/// <inheritdoc />", StringComparison.Ordinal);
        var headerIdx = result.IndexOf("public override string ToString()", StringComparison.Ordinal);
        inheritIdx.ShouldBeLessThan(headerIdx);
    }

    [Fact]
    public void InheritDoc_BlockScope_WithCref_InsertsBeforeHeader()
    {
        var q = new Quill();
        using (q.Block("public void Foo()").InheritDoc("IBar.Foo"))
        {
            q.Line("// body");
        }

        var result = q.Inscribe();
        result.ShouldContain("/// <inheritdoc cref=\"IBar.Foo\" />");
    }

    // ── Standalone InheritDoc (existing — verify still works) ────────────

    [Fact]
    public void InheritDoc_Standalone_EmitsWithoutCref()
    {
        var q = new Quill();
        q.InheritDoc();
        q.Line("public int X { get; }");
        var result = q.Inscribe();

        result.ShouldContain("/// <inheritdoc />");
    }

    [Fact]
    public void InheritDoc_Standalone_EmitsWithCref()
    {
        var q = new Quill();
        q.InheritDoc("IFoo.Bar");
        q.Line("public int X { get; }");
        var result = q.Inscribe();

        result.ShouldContain("/// <inheritdoc cref=\"IFoo.Bar\" />");
    }

    // ── Example ──────────────────────────────────────────────────────────

    [Fact]
    public void Example_Standalone_EmitsSingleLine()
    {
        var q = new Quill();
        q.Example("var x = Amount.Create(42m);");
        q.Line("public static Amount Create(decimal value) => new(value);");
        var result = q.Inscribe();

        result.ShouldContain("/// <example>var x = Amount.Create(42m);</example>");
    }

    [Fact]
    public void Example_Standalone_EmitsMultiLine()
    {
        var q = new Quill();
        q.Example("var x = 1;\nvar y = 2;");
        var result = q.Inscribe();

        result.ShouldContain("/// <example>");
        result.ShouldContain("///     var x = 1;");
        result.ShouldContain("///     var y = 2;");
        result.ShouldContain("/// </example>");
    }

    [Fact]
    public void Example_BlockScope_InsertsBeforeHeader()
    {
        var q = new Quill();
        using (q.Block("public static Amount Create(decimal value)").Example("Amount.Create(42m);"))
        {
            q.Line("return new(value);");
        }

        var result = q.Inscribe();
        result.ShouldContain("/// <example>Amount.Create(42m);</example>");
        var exampleIdx = result.IndexOf("/// <example>", StringComparison.Ordinal);
        var headerIdx = result.IndexOf("public static Amount Create", StringComparison.Ordinal);
        exampleIdx.ShouldBeLessThan(headerIdx);
    }

    // ── Exception ────────────────────────────────────────────────────────

    [Fact]
    public void Exception_Standalone_EmitsExceptionDoc()
    {
        var q = new Quill();
        q.Exception("ArgumentException", "Thrown when value is invalid.");
        q.Line("public static Amount Create(decimal value) => new(value);");
        var result = q.Inscribe();

        result.ShouldContain(
            "/// <exception cref=\"ArgumentException\">Thrown when value is invalid.</exception>"
        );
    }

    [Fact]
    public void Exception_BlockScope_InsertsBeforeHeader()
    {
        var q = new Quill();
        using (
            q.Block("public static Amount Create(decimal value)")
                .Summary("Creates an Amount.")
                .Exception("ArgumentException", "Value is bad.")
        )
        {
            q.Line("return new(value);");
        }

        var result = q.Inscribe();
        result.ShouldContain("/// <summary>Creates an Amount.</summary>");
        result.ShouldContain(
            "/// <exception cref=\"ArgumentException\">Value is bad.</exception>"
        );
        var summaryIdx = result.IndexOf("/// <summary>", StringComparison.Ordinal);
        var exceptionIdx = result.IndexOf("/// <exception", StringComparison.Ordinal);
        var headerIdx = result.IndexOf("public static Amount Create", StringComparison.Ordinal);
        summaryIdx.ShouldBeLessThan(exceptionIdx);
        exceptionIdx.ShouldBeLessThan(headerIdx);
    }

    // ── SeeAlso ──────────────────────────────────────────────────────────

    [Fact]
    public void SeeAlso_Standalone_EmitsSeeAlsoDoc()
    {
        var q = new Quill();
        q.SeeAlso("Amount.Create");
        q.Line("public decimal Value { get; }");
        var result = q.Inscribe();

        result.ShouldContain("/// <seealso cref=\"Amount.Create\" />");
    }

    [Fact]
    public void SeeAlso_BlockScope_InsertsBeforeHeader()
    {
        var q = new Quill();
        using (q.Block("public void Foo()").Summary("Does foo.").SeeAlso("Bar"))
        {
            q.Line("// body");
        }

        var result = q.Inscribe();
        result.ShouldContain("/// <seealso cref=\"Bar\" />");
        var seeAlsoIdx = result.IndexOf("/// <seealso", StringComparison.Ordinal);
        var headerIdx = result.IndexOf("public void Foo()", StringComparison.Ordinal);
        seeAlsoIdx.ShouldBeLessThan(headerIdx);
    }

    // ── Attribute (standalone — for one-liner members) ─────────────────

    [Fact]
    public void Attribute_Standalone_EmitsSimpleAttribute()
    {
        var q = new Quill();
        q.Attribute("Obsolete");
        q.Line("public void Foo() { }");
        var result = q.Inscribe();

        result.ShouldContain("[Obsolete]");
    }

    [Fact]
    public void Attribute_Standalone_EmitsAttributeWithArgs()
    {
        var q = new Quill();
        q.Attribute("Obsolete", "\"Use Bar instead.\"");
        q.Line("public void Foo() { }");
        var result = q.Inscribe();

        result.ShouldContain("[Obsolete(\"Use Bar instead.\")]");
    }

    [Fact]
    public void Attribute_Standalone_RespectsIndentation()
    {
        var q = new Quill();
        using (q.Block("public class Foo"))
        {
            q.Attribute("JsonPropertyName", "\"bar\"");
            q.Line("public string Bar { get; set; }");
        }

        var result = q.Inscribe();
        result.ShouldContain("    [JsonPropertyName(\"bar\")]");
        result.ShouldContain("    public string Bar { get; set; }");
    }

    // ── Attribute (BlockScope post-decoration) ───────────────────────────

    [Fact]
    public void Attribute_BlockScope_InsertsBeforeHeader()
    {
        var q = new Quill();
        using (q.Block("public class Foo").Attribute("Serializable"))
        {
            q.Line("public int X { get; }");
        }

        var result = q.Inscribe();
        result.ShouldContain("[Serializable]");
        var attrIdx = result.IndexOf("[Serializable]", StringComparison.Ordinal);
        var headerIdx = result.IndexOf("public class Foo", StringComparison.Ordinal);
        attrIdx.ShouldBeLessThan(headerIdx);
    }

    [Fact]
    public void Attribute_BlockScope_WithArgs()
    {
        var q = new Quill();
        using (q.Block("public void Foo()").Attribute("Obsolete", "\"Use Bar\""))
        {
            q.Line("// body");
        }

        var result = q.Inscribe();
        result.ShouldContain("[Obsolete(\"Use Bar\")]");
    }

    [Fact]
    public void Attribute_BlockScope_AfterXmlDoc()
    {
        var q = new Quill();
        using (
            q.Block("public void Foo()")
                .Summary("Does foo.")
                .Attribute("Obsolete", "\"Use Bar\"")
        )
        {
            q.Line("// body");
        }

        var result = q.Inscribe();
        var summaryIdx = result.IndexOf("/// <summary>", StringComparison.Ordinal);
        var attrIdx = result.IndexOf("[Obsolete", StringComparison.Ordinal);
        var headerIdx = result.IndexOf("public void Foo()", StringComparison.Ordinal);
        summaryIdx.ShouldBeLessThan(attrIdx);
        attrIdx.ShouldBeLessThan(headerIdx);
    }

    [Fact]
    public void Attribute_BlockScope_RespectsIndentation()
    {
        var q = new Quill();
        using (q.Block("public class Outer"))
        {
            using (q.Block("public void Inner()").Attribute("MethodImpl", "MethodImplOptions.AggressiveInlining"))
            {
                q.Line("// body");
            }
        }

        var result = q.Inscribe();
        result.ShouldContain("    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        result.ShouldContain("    public void Inner()");
    }

    // ── Region ───────────────────────────────────────────────────────────

    [Fact]
    public void Region_EmitsRegionAndEndRegion()
    {
        var q = new Quill();
        using (q.Region("Properties"))
        {
            q.Line("public int X { get; }");
        }

        var result = q.Inscribe();
        result.ShouldContain("#region Properties");
        result.ShouldContain("public int X { get; }");
        result.ShouldContain("#endregion");
    }

    [Fact]
    public void Region_RespectsIndentation()
    {
        var q = new Quill();
        using (q.Block("public class Foo"))
        {
            using (q.Region("Methods"))
            {
                q.Line("public void Bar() { }");
            }
        }

        var result = q.Inscribe();
        result.ShouldContain("    #region Methods");
        result.ShouldContain("    public void Bar() { }");
        result.ShouldContain("    #endregion");
    }

    [Fact]
    public void Region_NestedRegions()
    {
        var q = new Quill();
        using (q.Region("Outer"))
        {
            q.Line("// outer content");
            using (q.Region("Inner"))
            {
                q.Line("// inner content");
            }
        }

        var result = q.Inscribe();
        result.ShouldContain("#region Outer");
        result.ShouldContain("#region Inner");
        // Should have two #endregion
        var count = result.Split("#endregion").Length - 1;
        count.ShouldBe(2);
    }
}
